name: Call Render Endpoint Every 10 Minutes

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minute (UTC time)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Hybrid Search Endpoint
        run: curl https://hybridsearchdmp.onrender.com/
      - name: Call Another Endpoint
        run: curl https://newsearchtool.onrender.com/
      - name: Call Yet Another Endpoint
        run: curl https://huggingface.co/spaces/ShashankSS1205/SpanishOCR
      - name: Call Yet 2nd Another Endpoint
        run: curl https://spanishocr-renaissance.tiiny.site/
