name: Call Render Endpoint Every 10 Minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 minutes (UTC time)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Endpoint
        run: curl https://hybridsearchdmp.onrender.com/
